name: Release Artifacts

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Nodejs 19.4
        uses: actions/setup-node@v3
        with:
          node-version: 19.4
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.1
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Build popup
        working-directory: ./popup
        run: pnpm build
      - name: Zip extension
        working-directory: ./
        run: zip -r extension.zip popup/dist/ manifest.json images/ LICENSE README.md
      - name: Upload extension
        uses: actions/upload-artifact@v2
        with:
          name: epitech-competencies-stats
          path: epitech-competencies-stats.zip
      - name: Add release assets
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: epitech-competencies-stats.zip
          asset_name: epitech-competencies-stats.zip
          tag: ${{ github.ref }}
          overwrite: true
